# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-jar:
    desc: Build a fat JAR ready to run
    cmd: cd javalin && ./mvnw clean package -DskipTests
  
  build-native:
    desc: Build a binary-native image
    cmd: cd javalin && time ./mvnw -Pnative package

  run-dev:
    desc: Run the app in dev mode
    cmd: |
      cd javalin && \
      ./mvnw clean package -DskipTests && \
      doppler run --config dev -- bash -c '
        export ORDER_DB_URL="$DB_CONN" && \
        export ORDER_DB_USER="$DB_USER" && \
        export ORDER_DB_PASSWORD="$DB_PASS" && \
        java \
          -Dorg.slf4j.simpleLogger.log.com.thermcampos="info" \
          -jar target/javalin-1.0-SNAPSHOT.jar
      '

  run-native-tracing:
    desc: Buidl and run with native agent to trace reflections
    cmds:
      - |
        cd javalin && \
        ./mvnw clean package -DskipTests && \
        java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
        -jar target/javalin-1.0-SNAPSHOT.jar

  run-native:
    desc: Run the native binary
    cmd: export ORDER_DB_MIGRATIONS_PATH="javalin/db/migration" && ./javalin/target/app-native

  test:
    desc: Run tests
    cmd: cd javalin && ./mvnw test

  db-up:
    desc: Starts the database using Docker
    cmd: doppler run --config dev -- docker compose up -d

  db-down:
    desc: Stops the database using Docker
    cmd: doppler run --config dev -- docker compose down

